{% set version = "1.0" %}

package:
    name: polyview
    version: {{ version }}

source:
    git_url: https://github.com/oleg-alexandrov/PolyView.git
    #git_url: git@github.com:oleg-alexandrov/PolyView.git 
  
build:
    number: 0

requirements:
    build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - ninja
#        - m2w64-gcc
        - git
#        - make
        - qt=5.9.7
        
    host:
        - qt=5.9.7

    run:
        - qt=5.9.7

test: 
    files: 
        imports: 
        commands: 
        comment: "Need to add a test"
        
about: 
    home: https://github.com/oleg-alexandrov/PolyView
    license: MIT
    summary: "PolyView: a free and fast 2D polygon viewer and editor"

extra: 
  recipe-maintainers:
    - oleg.alexandrov@gmail.com
