name: qtenv
channels:
  - conda-forge
  - default

dependencies:
  - qt=5.9.7
  - git
  - ninja
  - conda-build
  - cmake

# Likely above do not need qt, that will be fetched later
# What we need mostly is conda-build
