name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  RELEASE_DIR: polyview_release_${RUNNER_OS}
  
jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
       os: [ubuntu-latest, macos-latest]       
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          activate-environment: qtenv
          environment-file: environment.yml
          auto-activate-base: false
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}

      - name: Step 1 - Create the directory which will store the release
        run: mkdir polyview_release

      - name: Install Packages
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then        
            sudo apt-get update -qq
            sudo apt-get install -y libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libxext-dev libxfixes-dev libgl1-mesa-dev
          fi
          
      - name: Check build environment
        run: |
          conda list
      - name: Build Package
        run: |
          qmake polyview.pro
          make
          make install INSTALL_ROOT=${RELEASE_DIR}

      - name: Test Package
        run: |
          echo Empty test

      - name: Upload
        uses: actions/upload-artifact@v2
        with: 
          name: ${RELEASE_DIR}
          path: ${RELEASE_DIR}
          
