name: UnixCondaBuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  LINUX_VERSION: ubuntu-18.04

jobs:
  UnixCondaBuild:
    name: UnixCondaBuild
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
       os: [${{ env.LINUX_VERSION }}, macos-latest]

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        activate-environment: buildenv
        environment-file: conda_build_env.yml
        auto-activate-base: false
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}

    - name: Install Packages
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then        
          sudo apt-get update -qq
          sudo apt-get install -y libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libxext-dev libxfixes-dev libgl1-mesa-dev
        fi

    - name: Build Package
      run: |
        conda build .
 
    - name: Test Package
      run: |
        echo Empty test

    - name: Upload Linux
      if: matrix.os == ${{ env.LINUX_VERSION }}
      uses: actions/upload-artifact@v2
      with: 
         name: polyview_${{ matrix.os }}_conda_build
         path: "/usr/share/miniconda3/envs/buildenv/conda-bld/linux-64"

    - name: Upload OSX
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v2
      with: 
          name: polyview_${{ matrix.os }}_conda_build
          path: "/Users/runner/miniconda3/envs/buildenv/conda-bld/osx-64"
